import { trackingConfig } from "../config/tracking";

let nextSectionNumber = 8;
const allServicesInactive = !Object.values(trackingConfig.providerRelease).some(Boolean);

const numberedSection = (id: string, title: string, body: string) => {
  const sectionNumber = nextSectionNumber;
  nextSectionNumber += 1;
  return `<h2 id="${id}">${sectionNumber}. ${title}</h2>\n${body}`;
};

const inactiveProviders = {
  "google-tag-manager": 'Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland. <a href="https://policies.google.com/privacy?hl=de">Datenschutzerklärung von Google</a>',
  "google-analytics": 'Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland. <a href="https://policies.google.com/privacy?hl=de">Datenschutzerklärung von Google</a>',
  "google-ads": 'Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland. <a href="https://policies.google.com/privacy?hl=de">Datenschutzerklärung von Google</a>',
  "meta-pixel": 'Meta Platforms Ireland Limited, Merrion Road, Dublin 4, D04 X2K5, Irland. <a href="https://www.facebook.com/privacy/policy/">Datenschutzerklärung von Meta</a>',
  "microsoft-clarity": 'Microsoft Ireland Operations Limited, One Microsoft Place, South County Business Park, Leopardstown, Dublin 18, Irland. <a href="https://www.microsoft.com/de-de/privacy/privacystatement">Datenschutzerklärung von Microsoft</a>',
  "openai-ads": 'OpenAI Ireland Limited. <a href="https://openai.com/policies/privacy-policy/">Datenschutzerklärung und Kontakt von OpenAI</a>',
};
const serviceSection = (section: string, enabled: boolean, status: string) => {
  if (enabled) return section;
  const id = section.match(/id="([^"]+)"/)?.[1] as keyof typeof inactiveProviders;
  return `${section.slice(0, section.indexOf("</h2>") + 5)}
<p>${status} Es werden für diesen Dienst keine neuen Messdaten erhoben oder gesendet. Eine frühere Einwilligung aktiviert ihn nicht.</p>
<p>Anbieter: ${inactiveProviders[id] || ""}.</p>
<p>Bereits zuvor an den Anbieter übermittelte Daten werden durch diese Abschaltung nicht automatisch gelöscht. Für Auskunft und Löschung können Sie sich an <a href="mailto:info@artbild-fotografie.de">info@artbild-fotografie.de</a> wenden.</p>`;
};

const consentSection = numberedSection(
  "cookies-und-einwilligungen",
  "Cookies und Einwilligungen",
  `<p>Für technisch nicht erforderliche Statistik- und Marketingdienste holen wir vor dem Laden des jeweiligen Dienstes Ihre Einwilligung ein. Statistik und Marketing können getrennt gewählt werden. Die Datenschutzeinstellungen führen Google Analytics, Google Ads, Microsoft Clarity, Meta Pixel und OpenAI Ads einzeln auf. ${allServicesInactive ? "Derzeit sind diese Dienste deaktiviert und können nicht eingeschaltet werden." : "Freigegebene Dienste können Sie im Banner einzeln auswählen."} Eine Ablehnung hat keinen Einfluss auf die grundlegende Nutzung dieser Website.</p>
<p>Eine von Ihnen getroffene Auswahl wird im Cookie <code>artbild_consent</code> gespeichert, das ausschließlich von dieser Website gesetzt wird. Das Cookie enthält die gewählten Services, eine Versionsangabe und den Zeitpunkt Ihrer Entscheidung. Es enthält weder Kontaktdaten noch Inhalte aus Formularen und hat eine maximale Laufzeit von 180 Tagen.</p>
<p>Die Speicherung dieser Auswahl ist erforderlich, um Ihre Entscheidung zu beachten. Der Versionsstand verweist auf die zugehörigen Hinweise; ein zusätzliches zentrales Besucherregister führen wir dafür nicht. Sie beruht auf Art. 6 Abs. 1 lit. c DSGVO in Verbindung mit Art. 7 Abs. 1 DSGVO sowie § 25 Abs. 2 Nr. 2 TDDDG. Über „Datenschutz-Einstellungen“ können Sie Ihre Auswahl jederzeit ändern. Ein Widerruf wirkt für die Zukunft.</p>
<p>Nur freigegebene Dienste werden nach Ihrer gesonderten Einwilligung geladen. Derzeit deaktivierte Dienste sind im Banner gekennzeichnet und werden auch bei „Alle akzeptieren“ nicht geladen. ${allServicesInactive ? "Auch der Google Tag Manager ist derzeit deaktiviert." : "Google Analytics, Google Ads, Microsoft Clarity und Meta Pixel werden direkt eingebunden. Der Google Tag Manager wird nicht geladen."}${trackingConfig.openaiAdsConfigured ? " OpenAI Ads wird separat eingebunden und benötigt keine Zustimmung zu den anderen Anbietern." : ""} Einzelheiten finden Sie in den folgenden Abschnitten.</p>`,
);

const tagManagerSection = numberedSection(
  "google-tag-manager",
  "Google Tag Manager",
  `<p>Der Google Tag Manager steuert auf dieser Website die einwilligungsabhängige Auslösung von Microsoft Clarity und Meta Pixel und erhält die dafür benötigten Einwilligungssignale. Google Analytics wird direkt eingebunden. Anbieter für Personen im Europäischen Wirtschaftsraum ist Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland.</p>
<p>Wir verwenden den grundlegenden Einwilligungsmodus von Google. Vor Ihrer Einwilligung wird der Tag Manager vollständig blockiert; es wird weder das Tag-Manager-Skript abgerufen noch werden Einwilligungssignale oder Messdaten an Google übertragen. Wenn Sie Microsoft Clarity oder Meta Pixel auswählen, wird der Tag Manager als technische Abhängigkeit mit geladen. Sobald Sie beide Dienste abwählen, wird auch der Tag Manager deaktiviert.</p>
<p>Beim Abruf des Tag Managers können insbesondere IP-Adresse, Datum und Uhrzeit sowie Browser-, Betriebssystem- und Geräteangaben als gewöhnliche HTTP-Protokolldaten an Google übermittelt werden. Die von dieser Website bereitgestellten Messereignisse enthalten keine Werte aus Formularfeldern. Google gibt an, die HTTP-Protokolldaten innerhalb von 14 Tagen nach ihrem Eingang zu löschen. Daneben kann Google aggregierte Diagnosedaten zur Stabilität und Ausführungsqualität von Tags verarbeiten; diese enthalten nach Angaben von Google keine IP-Adressen oder personenbezogenen Messkennungen.</p>
<p>Der Tag Manager wird ausschließlich auf Grundlage Ihrer Einwilligung nach Art. 6 Abs. 1 lit. a DSGVO geladen; soweit Informationen auf Ihrem Endgerät gespeichert oder ausgelesen werden, gilt zusätzlich § 25 Abs. 1 TDDDG. Weitere Angaben enthalten Googles Dokumentation zum <a href="https://developers.google.com/tag-platform/security/concepts/consent-mode?hl=de" rel="noopener noreferrer" target="_blank">Einwilligungsmodus</a>, die Hinweise zu <a href="https://support.google.com/tagmanager/answer/9323295?hl=de" rel="noopener noreferrer" target="_blank">Datenschutz und Sicherheit im Tag Manager</a> sowie die <a href="https://policies.google.com/privacy?hl=de" rel="noopener noreferrer" target="_blank">Datenschutzerklärung von Google</a>.</p>`,
);

const googleAnalyticsSection = numberedSection(
  "google-analytics",
  "Google Analytics",
  `<p>Google Analytics soll uns zeigen, wie häufig Seiten aufgerufen werden und wie Besucherinnen und Besucher durch das Angebot navigieren. Anbieter für Personen im Europäischen Wirtschaftsraum ist Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland.</p>
<p>Übermittelt werden können insbesondere IP-Adresse, aufgerufene Seiten, Referrer, Zeitpunkt und Dauer von Aufrufen, Interaktionen mit Seitenelementen, ungefähre Region sowie Angaben zu Browser, Betriebssystem und Gerät. Hinzu kommen pseudonyme Nutzer- und Sitzungskennungen. Die von dieser Website erzeugten Messereignisse enthalten keine Namen, E-Mail-Adressen, Nachrichten oder hochgeladenen Dateien aus unseren Formularen.</p>
<p>Google Analytics wird erst nach Ihrer Einwilligung in den Service „Google Analytics“ geladen. Ohne diese Einwilligung werden keine Analytics-Messsignale an Google übertragen. Nach Ihrer Einwilligung wird <code>analytics_storage</code> freigegeben und die cookie-basierte Statistikverarbeitung aktiviert. Für die Verarbeitung gelten Art. 6 Abs. 1 lit. a DSGVO und § 25 Abs. 1 TDDDG. Sie können die Einwilligung jederzeit über „Datenschutz-Einstellungen“ für die Zukunft widerrufen.</p>
<p>Die Laufzeit der mit <code>_ga</code> beginnenden Analytics-Cookies ist bei uns auf höchstens 180 Tage ab Setzen begrenzt und wird nicht bei jedem Aufruf verlängert. Die Aufbewahrungsfrist für Nutzer- und Ereignisdaten in unserer Analytics-Property beträgt 14 Monate. Bei erneuter Aktivität wird die Aufbewahrungsfrist der Nutzerkennung zurückgesetzt. Nach Ablauf löscht Google die betroffenen Daten im monatlichen Verfahren. Aggregierte Standardberichte sind nach Angaben von Google von dieser Frist nicht erfasst. Weitere Informationen finden Sie in den <a href="https://support.google.com/analytics/answer/7667196?hl=de" rel="noopener noreferrer" target="_blank">Hinweisen zur Datenaufbewahrung</a> und der <a href="https://policies.google.com/privacy?hl=de" rel="noopener noreferrer" target="_blank">Datenschutzerklärung von Google</a>.</p>`,
);


const googleAdsSection = numberedSection(
  "google-ads",
  "Google Ads und Conversion-Tracking",
  `<p>${trackingConfig.providerRelease.googleAds ? "Nach Ihrer gesonderten Einwilligung in Google Ads ordnen wir erfolgreich vom Server bestätigte Kontaktanfragen unseren Google-Anzeigen zu." : "Google Ads ist auf dieser Website derzeit deaktiviert. Es werden darüber keine Messdaten gesendet. Die nachfolgend beschriebene Messung wird erst nach ihrer Freigabe und Ihrer gesonderten Einwilligung aktiviert."} Anbieter ist Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland.</p>
<p>Die Messung verwendet eine Anzeigen-Klickkennung, technische Online-Kennungen, die bereinigte Seitenadresse, den Ereignistyp und Zeitpunkt sowie erforderliche Browser- und Geräteinformationen. Beim Verbindungsaufbau wird technisch Ihre IP-Adresse an Google übertragen. Wir senden dafür keine Namen, E-Mail-Adressen, Telefonnummern, Nachrichten, Hochzeitstermine, Veranstaltungsorte oder Hashwerte solcher Angaben. Ein bloßer Besuch der Kontaktseite und fehlgeschlagene Anfragen zählen nicht als erfolgreiche Kontaktanfrage.</p>
<p>Die Einwilligung in Google Ads ist unabhängig von Google Analytics, Meta, Microsoft Clarity und OpenAI. Ohne Google-Ads-Einwilligung bleibt der Dienst vollständig gesperrt; auch Messsignale ohne Cookies werden nicht gesendet. Rechtsgrundlagen sind § 25 Abs. 1 TDDDG für Endgerätezugriffe und Art. 6 Abs. 1 lit. a DSGVO für die Verarbeitung. Die Konfiguration verwendet keine erweiterten Conversions, keinen Kundenlisten-Abgleich, kein Remarketing und keine personalisierte Google-Werbung.</p>
<p>Cookies mit dem Präfix <code>_gcl_</code> dienen der Zuordnung eines Anzeigenklicks und haben in dieser Einbindung eine Laufzeit von höchstens 90 Tagen. Der Zuordnungszeitraum nach Anzeigenklick beträgt 30 Tage, für gegebenenfalls verwendete Sichtkontakte einen Tag. Zuordnungsfenster und Cookie-Laufzeiten sind keine allgemeinen Löschfristen für die bei Google gespeicherten Daten.</p>
<p>Google nennt für die Verfügbarkeit von Ads-Berichten seit Juni 2026 37 Monate für Stunden-, Tages- und Wochenwerte sowie elf Jahre für Monats-, Quartals- und Jahreswerte; Reichweiten- und Häufigkeitsdaten sind drei Jahre verfügbar. Für bestimmte Werbe-Serverprotokolle beschreibt Google eine teilweise Anonymisierung von IP-Adressen nach neun Monaten und die Entfernung von Cookie-Informationen nach 18 Monaten. Daraus folgt keine Zusage der vollständigen Löschung sämtlicher Ads-Daten nach diesen Fristen. Informationen enthalten die <a href="https://support.google.com/google-ads/answer/15188209?hl=de">Hinweise zur Berichtsaufbewahrung</a>, die <a href="https://policies.google.com/technologies/retention?hl=de">Aufbewahrungsinformationen von Google</a> und die <a href="https://policies.google.com/technologies/cookies?hl=de">Cookie-Hinweise</a>.</p>
<p>Google ordnet die Standarddienste zur Anzeigenmessung seinen Diensten mit eigenständiger Verantwortlichkeit zu. Einzelheiten enthalten die <a href="https://business.safety.google/adsservices/">vertragliche Diensteübersicht</a> und die <a href="https://business.safety.google/adscontrollerterms/">Datenschutzbedingungen zwischen Verantwortlichen</a>. Google Analytics hat eine andere vertragliche Einordnung. Mögliche Drittlandübermittlungen sind im Abschnitt „Drittlandübermittlungen“ beschrieben.</p>
<p>Sie können Ihre Einwilligung jederzeit über „Datenschutz-Einstellungen“ für die Zukunft widerrufen. Wir beenden weitere Messungen und entfernen zugängliche eigene Messcookies. Bereits an Google gesendete Daten werden dadurch nicht automatisch gelöscht; Cookies auf fremden Domains können wir nicht unmittelbar entfernen. Für Auskunft und Löschung können Sie sich an uns oder an Google wenden. Weitere Informationen: <a href="https://policies.google.com/privacy?hl=de">Datenschutzerklärung von Google</a>.</p>`,
);

const metaTrackingSection = numberedSection(
  "meta-pixel",
  "Meta Pixel",
  `<p>Das Meta Pixel soll die Reichweite und Wirksamkeit unserer Werbung auf Angeboten von Meta messen sowie die Bildung von Zielgruppen und Remarketing ermöglichen. Anbieter für Personen im Europäischen Wirtschaftsraum ist Meta Platforms Ireland Limited, Merrion Road, Dublin 4, D04 X2K5, Irland.</p>
<p>Übermittelt werden können insbesondere IP-Adresse, aufgerufene Seite, Referrer, Zeitpunkt des Aufrufs, Browser- und Geräteangaben, Cookie-Kennungen sowie von uns festgelegte Ereignisse: Seitenaufrufe, Kontaktklicks, das Ansehen von Preisen und erfolgreich abgesendete Kontaktanfragen. Bei einer bestätigten Anfrage übermitteln wir eine zufällige Ereigniskennung zur Vermeidung doppelter Messungen. Formularinhalte, hochgeladene Dateien und daraus gebildete Hashwerte werden nicht übergeben. Der automatische erweiterte Abgleich, automatische Events und das automatische Auslesen von Seiteninformationen sind deaktiviert. Seiten mit URL-Fragmenten oder anderen URL-Parametern als der Meta-Klickkennung fbclid, entsprechende Verweisadressen sowie dynamische Portfolio- und Kirchenfinder-Filterseiten sind ausgenommen.</p>
<p>Das Meta Pixel wird direkt und ausschließlich nach Ihrer gesonderten Einwilligung in den Service „Meta Pixel“ geladen. Eine Zustimmung zu Google, Clarity oder OpenAI aktiviert es nicht. Rechtsgrundlagen sind Art. 6 Abs. 1 lit. a DSGVO und § 25 Abs. 1 TDDDG. Sie können die Einwilligung jederzeit über „Datenschutz-Einstellungen“ für die Zukunft widerrufen.</p>
<p>Soweit Meta die Ereignisdaten für Zielgruppen-, Werbe- oder Remarketingzwecke zu eigenen Zwecken verarbeitet, sind wir und Meta Platforms Ireland Limited für die Erhebung auf dieser Website und die anschließende Übermittlung gemeinsam verantwortlich. Die Aufteilung der Pflichten für diesen Verarbeitungsschritt beschreibt das <a href="https://www.facebook.com/legal/controller_addendum" rel="noopener noreferrer" target="_blank">Controller Addendum von Meta</a>. Betroffenenrechte können sowohl bei uns als auch bei Meta geltend gemacht werden. Für die weitere Verarbeitung bei Meta sowie die dazugehörigen Informations- und Betroffenenrechte ist Meta verantwortlich.</p>
<p>Nach Ihrer Einwilligung in Meta Pixel werden eigene Cookies auf unserer Website verwendet: <code>_fbp</code> speichert eine Browserkennung zur Zuordnung von Seitenaufrufen und Conversions; <code>_fbc</code> speichert eine Meta-Anzeigenklickkennung, wenn ein entsprechender Anzeigenverweis vorhanden ist. Ihre Laufzeit beträgt bis zu 90 Tage und kann bei weiterer Nutzung nach gültiger Einwilligung erneuert werden. Vor Ihrer Meta-Einwilligung werden diese Cookies weder gesetzt noch zur Messung ausgelesen. Meta kann außerdem vorhandene Cookies auf seinen eigenen Domains nutzen, soweit Ihr Browser dies zulässt. Für die Zuordnung der Herkunft kann das Pixel die letzte externe Verweisquelle und ihren Zeitpunkt unter <code>lastExternalReferrer</code> und <code>lastExternalReferrerTime</code> im lokalen Browserspeicher ablegen. Wir entfernen diese Einträge beim Widerruf oder beim nächsten Seitenaufruf ohne gültige Einwilligung; Sie können sie auch über die Website-Daten Ihres Browsers löschen. Beim Widerruf beenden wir das Pixel und entfernen die zugänglichen eigenen Meta-Cookies; Cookies auf Meta-Domains können wir nicht unmittelbar löschen. Die Bedingungen für Meta-Unternehmenstools sehen für übermittelte Ereignisdaten eine Speicherdauer von höchstens zwei Jahren vor. Aus diesen Daten gebildete Zielgruppen bleiben bestehen, bis sie im Meta-Konto gelöscht werden. Weitere Angaben finden Sie in den <a href="https://www.facebook.com/legal/terms/businesstools" rel="noopener noreferrer" target="_blank">Bedingungen für Meta-Unternehmenstools</a>, der <a href="https://www.facebook.com/privacy/policies/cookies/" rel="noopener noreferrer" target="_blank">Cookie-Richtlinie</a> und der <a href="https://www.facebook.com/privacy/policy/" rel="noopener noreferrer" target="_blank">Datenschutzrichtlinie von Meta</a>.</p>`,
);

const claritySection = numberedSection(
  "microsoft-clarity",
  "Microsoft Clarity",
  `<p>Microsoft Clarity soll uns anhand von Heatmaps und nachgebildeten Nutzungssitzungen helfen, die Bedienbarkeit dieser Website zu beurteilen. Dabei handelt es sich nicht um eine Videoaufnahme Ihres Bildschirms, sondern um eine technische Rekonstruktion von Seitenelementen und Interaktionen. Anbieter für Personen im Europäischen Wirtschaftsraum ist Microsoft Ireland Operations Limited, One Microsoft Place, South County Business Park, Leopardstown, Dublin 18, Irland.</p>
<p>Übermittelt werden können insbesondere IP-Adresse, aufgerufene Seiten, Referrer, Datum und Uhrzeit, Klicks, Scrollbewegungen, Mausbewegungen, Fenstergröße, technische Fehler sowie Angaben zu Browser, Betriebssystem und Gerät. Clarity verarbeitet außerdem Seitenstruktur, Layout, Attribute und Inhalte nicht ausgeblendeter Seitenbereiche, soweit dies für die technische Rekonstruktion erforderlich ist. Wir verwenden eine strenge Textmaskierung und maskieren zusätzlich das gesamte Seitendokument. Inhalte aus Kontakt-, Anfrage- und Terminformularen werden nicht im Klartext für die Sitzungsrekonstruktion erfasst. Seitenaufrufe mit URL-Parametern oder Fragmenten, entsprechende Verweisadressen sowie die dynamischen Portfolio- und Kirchenfinder-Filterseiten werden von der Clarity-Messung ausgenommen.</p>
<p>Clarity wird direkt und nur nach der Einwilligung in den Service „Microsoft Clarity“ eingebunden. Es wird ausschließlich nach dieser Einwilligung geladen und erhält über die Consent API V2 ein freigegebenes Statistik- und ein abgelehntes Werbespeichersignal. Rechtsgrundlagen sind Art. 6 Abs. 1 lit. a DSGVO und § 25 Abs. 1 TDDDG. Sie können die Einwilligung jederzeit über „Datenschutz-Einstellungen“ für die Zukunft widerrufen. Microsoft Advertising (ehemals Bing Ads) und das UET-Tracking sind nicht Bestandteil der hier beschriebenen Clarity-Nutzung.</p>
<p>Microsoft führt für Clarity die First-Party-Cookies <code>_clck</code> zur Speicherung einer pseudonymen Clarity-Nutzer-ID und von Website-Einstellungen sowie <code>_clsk</code> zur Verbindung mehrerer Seitenaufrufe zu einer Sitzung auf. Ihre Laufzeiten betragen bis zu ein Jahr beziehungsweise bis zu einen Tag. Zusätzlich nennt Microsoft die möglichen Third-Party-Cookies <code>CLID</code> zur Erkennung des erstmaligen Kontakts eines Browsers mit Clarity, <code>ANONCHK</code> zur Kennzeichnung einer möglichen Übertragung der Microsoft-Nutzer-ID MUID an das von Clarity nicht verwendete Werbe-Cookie ANID, <code>MR</code> zur Steuerung der MUID-Aktualisierung, <code>MUID</code> zur pseudonymen Browsererkennung auf Microsoft-Domains und <code>SM</code> zur Synchronisierung der MUID über Microsoft-Domains. Ob Third-Party-Cookies technisch gespeichert werden können, hängt auch von den Browser- und Cookie-Einstellungen ab. Microsoft nennt in der aktuellen Clarity-Cookie-Liste für diese Third-Party-Cookies keine festen Laufzeiten; sie werden durch Microsoft sowie die Browser- und Cookie-Einstellungen bestimmt. Weitere Einzelheiten enthält die <a href="https://learn.microsoft.com/en-us/clarity/setup-and-installation/clarity-cookies" rel="noopener noreferrer" target="_blank">Cookie-Liste von Microsoft Clarity</a>.</p>
<p>Microsoft gibt derzeit folgende Speicherdauern an: Wiedergabedaten werden 30 Tage gespeichert; Klick- und Heatmap-Daten sowie markierte oder favorisierte Sitzungen werden neun Monate gespeichert. Weitere Informationen finden Sie in der <a href="https://learn.microsoft.com/en-us/clarity/setup-and-installation/data-retention" rel="noopener noreferrer" target="_blank">Clarity-Dokumentation zur Datenaufbewahrung</a> und der <a href="https://www.microsoft.com/de-de/privacy/privacystatement" rel="noopener noreferrer" target="_blank">Datenschutzerklärung von Microsoft</a>.</p>`,
);

const openaiAdsSection = numberedSection(
  "openai-ads",
  "OpenAI Ads – Messung von Anzeigen in ChatGPT",
  `<p>${trackingConfig.providerRelease.openaiAds ? "Nach Ihrer Einwilligung in „OpenAI Ads“ messen wir" : "OpenAI Ads ist derzeit deaktiviert. Nach Freigabe und Ihrer gesonderten Einwilligung dient der Dienst folgender Messung: Wir messen"} ausschließlich erfolgreich übermittelte Kontaktanfragen, um sie Anzeigen in ChatGPT zuzuordnen. Für Daten aus dem Europäischen Wirtschaftsraum ist nach den OpenAI-Werbebedingungen OpenAI Ireland Limited zuständig. Die Einwilligung ist unabhängig von Google, Microsoft und Meta und keine Voraussetzung für eine Kontaktanfrage.</p>
<p>Unser Messcode meldet erst nach bestätigter Annahme durch unseren Server eine erfolgreiche Kontaktanfrage. Eingabefelder werden von der OpenAI-Messung nicht ausgelesen. E-Mail-Adresse, Name, Telefonnummer, Nachricht, Hochzeitstermin, Veranstaltungsort und sonstige Formularinhalte werden dafür nicht an OpenAI übermittelt. Übertragen werden das Ereignis „Anfrage erfolgreich gesendet“, eine gegebenenfalls vorhandene Anzeigenkennung, der Ereigniszeitpunkt und die feste Adresse unserer Messseite ohne Abfrageparameter und Fragment. Das Pixel kann innerhalb dieser einzelnen Messung eine vorübergehende Zufallskennung erzeugen. Beim Verbindungsaufbau fallen technische Daten wie IP-Adresse und Browserangaben an.</p>
<p>Das OpenAI-Skript wird erst nach erfolgreichem Absenden in einem isolierten Bereich ohne Zugriff auf das Kontaktformular geladen. Seitenaufrufe, Eingaben und fehlgeschlagene Sendeversuche werden damit nicht an OpenAI gemeldet.</p>
<p>Die Verarbeitung und der Zugriff auf Ihr Endgerät erfolgen auf Grundlage Ihrer Einwilligung nach Art. 6 Abs. 1 lit. a DSGVO und § 25 Abs. 1 TDDDG. Vor Ihrer Zustimmung wird das OpenAI-Skript nicht geladen. Bei Widerruf über „Datenschutz-Einstellungen“ stoppen wir weitere Messungen, entfernen die nachfolgend genannten Kennungen und laden die Seite neu. Vor der Zustimmung blockierte Ereignisse werden später nicht nachgesendet.</p>
<p>Das First-Party-Cookie <code>__oppref</code> speichert eine Anzeigenzuordnung für bis zu 30 Tage; ein neuer Anzeigenverweis erneuert diese Frist. Eine dauerhafte OpenAI-Browserkennung wird in dieser Einbindung nicht gespeichert. Eine gegebenenfalls vorhandene Browserkennung aus der bisherigen Einbindung wird entfernt. Diese Laufzeiten beschreiben die Speicherung im Browser, nicht die Aufbewahrung bereits übermittelter Daten bei OpenAI. Der Auftragsverarbeitungsvertrag beschreibt hierfür die Vertragslaufzeit und eine anschließend für die Abwicklung einschließlich Löschung erforderliche Zeit; er sieht nach Vertragsende auf unsere Anweisung Rückgabe oder Löschung vor, vorbehaltlich gesetzlicher Aufbewahrungspflichten. Eine einheitliche Frist in Tagen für sämtliche Conversion-Daten ist nicht veröffentlicht. Für Auskunft oder Löschung können Sie sich an uns unter <a href="mailto:info@artbild-fotografie.de">info@artbild-fotografie.de</a> wenden; ein Widerruf stoppt künftige Übermittlungen und löscht nicht automatisch bereits bei OpenAI eingegangene Daten.</p>
<p>Ihre Auswahl im Cookie-Banner erlaubt OpenAI ausschließlich für die beschriebene Anzeigenmessung. Gleichzeitig widersprechen Sie einer künftigen nutzerbezogenen Personalisierung mit diesen Messdaten. Wir übermitteln diese Entscheidung mit jedem Ereignis durch den dokumentierten Opt-out. Die Zuordnung zu Anzeigen bleibt dabei möglich. Für diese mit einem personenbezogenen Widerspruch gekennzeichnete Verarbeitung von Daten aus dem EWR sieht der Datenschutz-Zusatz für Werbetools uns als Verantwortlichen und OpenAI als Auftragsverarbeiter vor; hierfür gilt auch der dort einbezogene Auftragsverarbeitungsvertrag. Außerhalb dieser eingeschränkten Verarbeitung sehen die Bedingungen eigenständige Verantwortlichkeiten vor.</p>
<p>OpenAI setzt für die eingeschränkte Verarbeitung Infrastruktur-, Auslieferungs- und Supportdienstleister sowie verbundene Unternehmen ein. Die aktuelle <a href="https://openai.com/policies/ad-tools-subprocessors/" rel="noopener noreferrer" target="_blank">Liste der Unterauftragsverarbeiter</a> nennt Empfänger, Aufgaben und Verarbeitungsländer. Eine Verarbeitung außerhalb des EWR, insbesondere in den USA, ist möglich. Für Übermittlungen zwischen verbundenen Unternehmen nennt OpenAI Standardvertragsklauseln; OpenAI Ireland sagt im Datenschutz-Zusatz gültige Übermittlungsmechanismen für Länder ohne angemessenes Schutzniveau zu. Eine ausschließliche Speicherung in der EU wird nicht zugesagt. Weitere Informationen enthalten die <a href="https://help.openai.com/en/articles/20001409-conversion-measurement" rel="noopener noreferrer" target="_blank">Hinweise zur Konversionsmessung</a>, die <a href="https://openai.com/policies/conversion-terms/" rel="noopener noreferrer" target="_blank">Konvertierungsbedingungen</a>, der <a href="https://openai.com/policies/ad-tools-dpa/" rel="noopener noreferrer" target="_blank">Datenschutz-Zusatz für Werbetools</a>, der <a href="https://openai.com/policies/data-processing-addendum/" rel="noopener noreferrer" target="_blank">Auftragsverarbeitungsvertrag</a>, die <a href="https://developers.openai.com/ads/measurement-pixel" rel="noopener noreferrer" target="_blank">Pixel-Dokumentation</a> und die <a href="https://openai.com/policies/privacy-policy/" rel="noopener noreferrer" target="_blank">Datenschutzerklärung von OpenAI</a>.</p>`,
);

const thirdCountrySection = numberedSection(
  "drittlanduebermittlungen-tracking",
  "Drittlandübermittlungen bei Statistik- und Marketingdiensten",
  `<p>Bei Google, Meta und Microsoft kann nicht ausgeschlossen werden, dass Daten an verbundene Unternehmen oder andere Empfänger außerhalb der Europäischen Union und des Europäischen Wirtschaftsraums, insbesondere in den USA, übermittelt oder dort verarbeitet werden.</p>
<p>Google LLC, Meta Platforms, Inc. und Microsoft Corporation sind nach den derzeitigen Angaben der Anbieter für das EU-US Data Privacy Framework zertifiziert. Für von der jeweiligen Zertifizierung erfasste Datenübermittlungen in die USA gilt deshalb der Angemessenheitsbeschluss der Europäischen Kommission. Die Anbieter informieren über ihre Zertifizierungen und Übermittlungsgrundlagen bei <a href="https://policies.google.com/privacy/frameworks?hl=de" rel="noopener noreferrer" target="_blank">Google</a>, <a href="https://www.facebook.com/privacy/policies/data_privacy_framework/" rel="noopener noreferrer" target="_blank">Meta</a> und <a href="https://www.microsoft.com/de-de/privacy/privacystatement" rel="noopener noreferrer" target="_blank">Microsoft</a>. Der aktuelle Status kann zusätzlich in der <a href="https://www.dataprivacyframework.gov/list" rel="noopener noreferrer" target="_blank">offiziellen Data-Privacy-Framework-Liste</a> geprüft werden.</p>
<p>Für Übermittlungen, die nicht von einem Angemessenheitsbeschluss erfasst sind, beschreiben die Anbieter weitere Schutzinstrumente. Google verweist in seinen <a href="https://policies.google.com/privacy/frameworks?hl=de" rel="noopener noreferrer" target="_blank">Rahmenbedingungen für Datenübermittlungen</a> auf EU-Standardvertragsklauseln. Meta veröffentlicht ein <a href="https://www.facebook.com/legal/terms/Privacy/GDTA" rel="noopener noreferrer" target="_blank">Global Data Transfer Addendum</a>. Microsoft erläutert die zwischen Microsoft Ireland Operations Limited und Microsoft Corporation verwendeten Standardvertragsklauseln in den <a href="https://learn.microsoft.com/en-us/clarity/faq" rel="noopener noreferrer" target="_blank">Datenschutzhinweisen zu Clarity</a>. Welche Übermittlungsgrundlage im Einzelfall greift, richtet sich nach Empfänger, Zielstaat und den jeweils geltenden Anbieterbedingungen.</p>
<p>Trotz solcher Instrumente kann bei einer Verarbeitung in einem Drittland ein Risiko bestehen, dass Behörden nach dem dortigen Recht auf Daten zugreifen und europäische Betroffenenrechte nicht in gleicher Weise durchgesetzt werden können.</p>`,
);

const picDropSection = numberedSection(
  "picdrop",
  "Kundengalerien über PicDrop",
  `<p>Für die Bereitstellung und Abstimmung von Kundengalerien verwenden wir PicDrop. Anbieter ist die PicDrop GmbH, Am Kupfergraben 4/4a, 10117 Berlin. Beim Aufruf einer separat bereitgestellten PicDrop-Galerie können insbesondere Bilder, Galerie- und Zugriffsdaten, IP-Adresse, Zeitpunkt, Referrer, Browserangaben sowie von Ihnen vorgenommene Auswahlen verarbeitet werden.</p>
<p>Die Verarbeitung erfolgt zur Vertragserfüllung nach Art. 6 Abs. 1 lit. b DSGVO und, soweit erforderlich, aufgrund unseres berechtigten Interesses an einer sicheren und übersichtlichen Bildauslieferung nach Art. 6 Abs. 1 lit. f DSGVO. PicDrop gibt für technische Protokolldaten eine Löschung nach 90 Tagen an. Die Bereitstellungsdauer einer Kundengalerie richtet sich nach der jeweiligen Vereinbarung; anschließend werden die Daten gelöscht, soweit keine gesetzlichen Pflichten oder berechtigten Gründe für eine weitere Aufbewahrung bestehen. Weitere Informationen finden Sie in der <a href="https://www.picdrop.com/web/de/privacy" rel="noopener noreferrer" target="_blank">Datenschutzerklärung von PicDrop</a>.</p>`,
);

const externalLinksSection = numberedSection(
  "externe-links",
  "Externe Links und soziale Netzwerke",
  `<p>Auf der Website befinden sich Links zu externen Angeboten, insbesondere Instagram, Facebook und Pinterest. Beim bloßen Anzeigen unserer Seiten wird durch diese Links keine Verbindung zum jeweiligen Netzwerk hergestellt. Erst wenn Sie einen externen Link öffnen, verarbeitet der jeweilige Anbieter den Aufruf nach seinen eigenen Datenschutzbestimmungen. Dies gilt ebenso für Schaltflächen, mit denen Inhalte bei einem sozialen Netzwerk geteilt werden.</p>`,
);

const storageSection = numberedSection(
  "speicherdauer",
  "Speicherdauer",
  `<p>Für jede Verarbeitung gilt: Entfällt der Zweck, werden die betreffenden personenbezogenen Daten gelöscht oder anonymisiert. Eine weitere Aufbewahrung erfolgt nur, wenn gesetzliche Fristen einzuhalten sind, Daten für die Geltendmachung oder Abwehr von Ansprüchen benötigt werden oder ein anderer gesetzlich zulässiger Grund fortbesteht.</p>`,
);

const rightsSection = numberedSection(
  "rechte",
  "Ihre Rechte",
  `<p>Sie haben im Rahmen der gesetzlichen Voraussetzungen insbesondere das Recht auf Auskunft nach Art. 15 DSGVO, Berichtigung nach Art. 16 DSGVO, Löschung nach Art. 17 DSGVO, Einschränkung der Verarbeitung nach Art. 18 DSGVO und Datenübertragbarkeit nach Art. 20 DSGVO. Eine erteilte Einwilligung können Sie jederzeit mit Wirkung für die Zukunft widerrufen.</p>
<p>Durch den Widerruf wird die Rechtmäßigkeit der Verarbeitung bis zum Zeitpunkt des Widerrufs nicht berührt. Sie können einer Verarbeitung, die auf Art. 6 Abs. 1 lit. f DSGVO beruht, aus Gründen Ihrer besonderen Situation nach Art. 21 DSGVO widersprechen. Gegen die Verarbeitung für Zwecke der Direktwerbung einschließlich eines damit verbundenen Profilings können Sie jederzeit widersprechen. Wenden Sie sich dazu an <a href="mailto:info@artbild-fotografie.de">info@artbild-fotografie.de</a>.</p>`,
);

const complaintSection = numberedSection(
  "beschwerderecht",
  "Beschwerderecht",
  `<p>Sie haben das Recht, sich bei einer Datenschutzaufsichtsbehörde zu beschweren. Für Hamburg ist dies der Hamburgische Beauftragte für Datenschutz und Informationsfreiheit. Aktuelle Kontaktdaten finden Sie unter <a href="https://datenschutz-hamburg.de/" rel="noopener noreferrer" target="_blank">datenschutz-hamburg.de</a>.</p>`,
);

const privacyContent = `
<p><strong>Stand: 1. Oktober 2026</strong></p>
<p>Diese Datenschutzerklärung erläutert, welche personenbezogenen Daten beim Besuch dieser Website und bei der Kontaktaufnahme verarbeitet werden.</p>

<h2 id="verantwortlicher">1. Verantwortlicher</h2>
<p>
  Artbild-Fotografie<br>
  York Augustin<br>
  Rahlstedter Bahnhofstraße 27<br>
  22143 Hamburg<br>
  Deutschland
</p>
<p>E-Mail: <a href="mailto:info@artbild-fotografie.de">info@artbild-fotografie.de</a></p>
<p>Weitere Angaben finden Sie im <a href="/impressum/">Impressum</a>.</p>

<h2 id="bunny-hosting">2. Webhosting bei bunny.net</h2>
<p>Für das Webhosting dieser Website nutzen wir bunny.net. Anbieter ist BunnyWay d.o.o. mit Sitz in der Dunajska cesta 165, 1000 Ljubljana, Slowenien.</p>
<p>Der von uns gewählte Standort des Webservers ist Frankfurt am Main, Deutschland. Auch die Datenbank dieser Website wird nach unserer Konfiguration ausschließlich in Frankfurt am Main gespeichert. Diese Standortangabe bezieht sich auf den Webserver und die Website-Datenbank.</p>
<p>Beim Besuch der Website werden insbesondere Ihre IP-Adresse, Datum und Uhrzeit des Aufrufs, die aufgerufene Seite oder Datei, die zuvor besuchte Seite (Referrer) sowie Angaben zu Browser, Betriebssystem und verwendetem Gerät an bunny.net übermittelt.</p>
<p>Die Verarbeitung erfolgt, um die Website bereitzustellen, ihre Stabilität und Sicherheit zu gewährleisten sowie Missbrauch und technische Fehler zu erkennen. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO. Unser berechtigtes Interesse liegt in einem sicheren und zuverlässigen Internetangebot.</p>
<p>Die Daten werden nur so lange gespeichert, wie dies für die genannten Zwecke erforderlich ist, sofern keine gesetzlichen Pflichten oder die Bearbeitung eines konkreten Sicherheitsvorfalls eine längere Speicherung erfordern. Weitere Informationen finden Sie in der <a href="https://bunny.net/privacy/" rel="noopener noreferrer" target="_blank">Datenschutzrichtlinie von bunny.net</a>.</p>

<h2 id="kontaktformular">3. Kontaktformular</h2>
<p>Wenn Sie das Kontaktformular verwenden, verarbeiten wir die von Ihnen eingegebenen Angaben. Pflichtangaben sind Anfrageart, Name, E-Mail-Adresse, Veranstaltungsort und die Antwort auf die Sicherheitsfrage. Das Wunschdatum ist außer bei TFP-Anfragen ebenfalls erforderlich. Nachricht und bis zu drei Bilddateien bei einer TFP-Anfrage sind freiwillig. Es besteht keine gesetzliche Pflicht, diese Daten bereitzustellen. Ohne die erforderlichen Angaben kann das Formular nicht versendet und die Anfrage nicht bearbeitet werden.</p>
<p>Wenn Sie eine Buchungsanfrage über die Agentenseite vorbereiten lassen, werden Anfrageart, Wunschdatum, Veranstaltungsort und ein optionaler Paketwunsch vorübergehend in Ihrem Browser bereitgehalten und beim Öffnen des Kontaktformulars übernommen. Der Entwurf wird nach der Übernahme oder spätestens nach 30 Minuten verworfen. Name, E-Mail-Adresse und Datenschutzbestätigung werden dabei nicht übernommen. Eine Übermittlung an uns erfolgt erst, wenn Sie das Kontaktformular selbst absenden.</p>
<p>Zusätzlich werden Zeitpunkt und Quellseite der Anfrage, die Antwort auf die Sicherheitsfrage, Anzahl und Dateinamen der Anhänge sowie eine aus der IP-Adresse gebildete pseudonymisierte Kennung verarbeitet. Die Inhalte hochgeladener Dateien werden für den Versand verarbeitet und als E-Mail-Anhang weitergegeben; sie werden nicht zusammen mit dem Formulardatensatz gespeichert.</p>
<p>Wir verwenden diese Daten, um Ihre Anfrage zu beantworten, ein gewünschtes Vertragsverhältnis vorzubereiten und das Formular gegen automatisierten Missbrauch zu schützen. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO, soweit Ihre Anfrage auf einen Vertrag oder vorvertragliche Maßnahmen gerichtet ist. Im Übrigen erfolgt die Verarbeitung nach Art. 6 Abs. 1 lit. f DSGVO aufgrund unseres Interesses an einer zuverlässigen und missbrauchsgeschützten Kommunikation.</p>
<p>Die Formulardaten werden im Rahmen des Webhostings in Frankfurt am Main vorübergehend gespeichert und an unser E-Mail-Postfach bei STRATO übermittelt. Die pseudonymisierte IP-Kennung dient ausschließlich der Begrenzung wiederholter Einsendungen und wird spätestens nach 30 Minuten entfernt. Sobald die Speicherdauer von 30 Tagen überschritten ist, wird die technische Datenbankkopie der Anfrage in einem regelmäßigen Bereinigungslauf automatisch gelöscht.</p>
<p>Die an STRATO übermittelte Korrespondenz speichern wir so lange, wie dies für die Bearbeitung der Anfrage, ein mögliches Vertragsverhältnis, die Erfüllung gesetzlicher Aufbewahrungspflichten oder die Geltendmachung beziehungsweise Abwehr von Ansprüchen erforderlich ist.</p>

<h2 id="email-versand">4. E-Mail-Kommunikation</h2>
<p>Für die Verarbeitung und Speicherung von E-Mails nutzen wir STRATO. Anbieter ist die STRATO GmbH, Otto-Ostrowski-Straße 7, 10249 Berlin. Beim Versand einer Kontaktanfrage werden die Formulardaten und etwaige Anhänge an unser dort geführtes E-Mail-Postfach übermittelt.</p>
<p>Wenn Sie uns per E-Mail kontaktieren, verarbeiten wir insbesondere Ihre E-Mail-Adresse, den Inhalt Ihrer Nachricht, etwaige Anhänge sowie die bei der E-Mail-Kommunikation anfallenden Verbindungs- und Zeitdaten. Bei einer Kontaktaufnahme per Telefon verarbeiten wir die von Ihnen mitgeteilten Daten zur Bearbeitung Ihres Anliegens. Es gelten dieselben Rechtsgrundlagen wie für das Kontaktformular. Weitere Informationen enthält die <a href="https://www.strato.de/datenschutz/" rel="noopener noreferrer" target="_blank">Datenschutzerklärung von STRATO</a>.</p>

<h2 id="whatsapp">5. Kontakt über WhatsApp</h2>
<p>Die Website enthält Links, über die Sie freiwillig einen WhatsApp-Chat mit uns beginnen können. Beim bloßen Anzeigen der Website wird keine Verbindung zu WhatsApp hergestellt. Erst wenn Sie den Link öffnen, werden Sie zu WhatsApp weitergeleitet. Dabei wird auch der im jeweiligen Link vorgegebene Nachrichtentext an WhatsApp übermittelt; Sie können ihn vor dem Absenden der Nachricht verändern.</p>
<p>Wenn Sie uns über WhatsApp kontaktieren, verarbeiten wir insbesondere Ihre Telefonnummer, Ihren Profilnamen, den Nachrichteninhalt, übermittelte Dateien sowie Kommunikationszeitpunkte zur Bearbeitung Ihrer Anfrage. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO, soweit es um einen Vertrag oder vorvertragliche Maßnahmen geht, ansonsten Art. 6 Abs. 1 lit. f DSGVO aufgrund unseres Interesses an einer von Ihnen gewählten, direkten Kommunikation.</p>
<p>Anbieter für die Region Europa ist WhatsApp Ireland Limited, Merrion Road, Dublin 4, D04 X2K5, Irland. WhatsApp verarbeitet zusätzlich eigene Konto-, Geräte-, Verbindungs- und Nutzungsdaten und kann Informationen weltweit übermitteln.</p>
<p>Nach der aktuellen Datenschutzrichtlinie von WhatsApp sind WhatsApp LLC und Meta Platforms, Inc. für das EU-US Data Privacy Framework zertifiziert. Für Übermittlungen, die nicht von einem Angemessenheitsbeschluss erfasst sind, gibt WhatsApp den Einsatz der von der Europäischen Kommission genehmigten Standardvertragsklauseln an. Einzelheiten finden Sie in der <a href="https://www.whatsapp.com/legal/privacy-policy-eea?lang=de_DE" rel="noopener noreferrer" target="_blank">Datenschutzrichtlinie von WhatsApp</a>.</p>

<h2 id="terminverfuegbarkeit">6. Terminverfügbarkeit</h2>
<p>Wenn Sie die öffentliche Terminabfrage nutzen, wird das von Ihnen ausgewählte Datum an den Server dieser Website übermittelt und dort mit bereits gesperrten Daten abgeglichen. Für diese Abfrage sind weder Ihr Name noch Ihre Kontaktdaten erforderlich.</p>
<p>Um die automatische Prüfung auf höchstens drei unterschiedliche Kalendertage innerhalb von 24 Stunden zu begrenzen, wird aus der beim Zugriff technisch übermittelten IP-Adresse unmittelbar mit einem geheimen Zusatz eine pseudonyme Kurzzeitkennung gebildet. Für diese Begrenzung werden nur die Kennung, die geprüften Daten und die Zeitpunkte der ersten Prüfung gespeichert. Wiederholte Prüfungen desselben Datums erhöhen die Anzahl nicht. Die vollständige IP-Adresse wird nicht gespeichert; abgelaufene Einträge werden im nächsten regelmäßigen Bereinigungslauf gelöscht.</p>

<p>Für die technische Nutzungs- und Missbrauchsauswertung protokollieren wir diese Terminprüfungen für höchstens 30 Tage: Zeitpunkt, angefragte Daten, Ergebnis, HTTP-Status, Zugangsweg (zum Beispiel FAB oder API) sowie eine abgeleitete Browser-, Bot- oder Dienst-Kategorie mit Herkunftshinweis. Eine Prüfung gegen öffentlich veröffentlichte Anbieter-IP-Bereiche erfolgt auf unserem Server; dabei wird die Absender-IP nicht an den Anbieter übermittelt oder in diesem Protokoll gespeichert. Es werden keine zusätzlichen Tracking-Cookies gesetzt. Ergänzend speichern wir die grobe Geräteklasse (Desktop, Mobilgerät, Tablet oder unbekannt) und eine daraus abgeleitete Einschätzung der Bedienungsart. Dafür verwenden wir Browserangaben und einfache Signale zur Formularbedienung, ausdrücklich gemeldeter Automatisierung oder WebMCP-Nutzung; diese Signale werden ohne zusätzliche Kennungen oder Besucherprofile verarbeitet. Browserabfragen lassen nicht zuverlässig erkennen, ob ein Mensch oder ein KI-Assistent den Browser bedient. Die Auswertung zeigt Häufigkeiten je Wunschtermin, getrennt nach mutmaßlich manueller Nutzung, Bot-Hinweisen und unklaren Abrufen.</p>

<h2 id="terminabfrage-buchungsagenten">7. Begrenzte Terminabfrage für Buchungsagenten</h2>
<p>Auf der Seite „Für Buchungsagenten“ können pro Anfrage ein bis drei konkrete Wunschdaten an den Server dieser Website übermittelt und mit bereits gesperrten Daten abgeglichen werden. Die zurückgegebene Auskunft ist unverbindlich und bewirkt weder eine Reservierung noch eine automatisierte Buchungsentscheidung.</p>
<p>Um die Schnittstelle auf höchstens zwei erfolgreiche Abfragen innerhalb von 24 Stunden zu begrenzen, wird aus der beim Zugriff technisch übermittelten IP-Adresse unmittelbar mit einem geheimen Zusatz eine pseudonyme Kurzzeitkennung gebildet. Für diese Begrenzung werden nur die Kennung und die Zeitpunkte erfolgreicher Abfragen gespeichert. Einträge, deren 24-Stunden-Fenster abgelaufen ist, werden im nächsten regelmäßigen Bereinigungslauf gelöscht.</p>
<p>Zusätzlich protokollieren wir für höchstens 30 Tage den Zugangsweg, eine abgeleitete Bot- oder Dienst-Kategorie sowie die Art und das Ergebnis einer optionalen technischen Herkunftsprüfung, die konkret angefragten Wunschdaten, das jeweilige Verfügbarkeitsergebnis, den HTTP-Status und den Zeitpunkt der Anfrage. Die vollständige IP-Adresse, der vollständige User-Agent und ein optional übermittelter API-Schlüssel werden nicht gespeichert. Bot-Kennungen und vom Hosting-Proxy übermittelte Anbieter-IP-Adressen sind Herkunftshinweise, keine sichere Identifizierung einer Person oder eines KI-Modells. Diese Hinweise werden in der geschützten Ansicht entsprechend gekennzeichnet; ein individuell zugewiesener API-Schlüssel kann die zugehörige Client-Kennzeichnung bestätigen.</p>
<p>Die Verarbeitung dient dazu, konkrete Buchungsprüfungen nachzuvollziehen, die Schnittstelle technisch zu betreiben, Fehler zu erkennen und automatisierte Massenabfragen oder eine Umgehung der Abfragegrenze zu verhindern. Soweit die Anfrage auf einen konkreten Vertrag oder vorvertragliche Maßnahmen gerichtet ist, ist Art. 6 Abs. 1 lit. b DSGVO die Rechtsgrundlage. Im Übrigen erfolgt die Verarbeitung nach Art. 6 Abs. 1 lit. f DSGVO aufgrund unseres berechtigten Interesses an einer zuverlässigen, nachvollziehbaren und missbrauchsgeschützten Terminabfrage.</p>

${consentSection}
${serviceSection(tagManagerSection, trackingConfig.metaViaTagManager || trackingConfig.clarityViaTagManager, "Der Google Tag Manager ist derzeit deaktiviert und wird nicht geladen.")}
${serviceSection(googleAnalyticsSection, trackingConfig.providerRelease.googleAnalytics, "Google Analytics zur Reichweitenanalyse ist derzeit deaktiviert.")}
${serviceSection(googleAdsSection, trackingConfig.providerRelease.googleAds, "Google Ads zur Messung von Anzeigen und erfolgreich übermittelten Kontaktanfragen ist derzeit deaktiviert.")}
${serviceSection(metaTrackingSection, trackingConfig.providerRelease.metaPixel, "Das Meta Pixel zur Werbemessung und personalisierten Werbung ist derzeit deaktiviert.")}
${serviceSection(claritySection, trackingConfig.providerRelease.microsoftClarity, "Microsoft Clarity ist derzeit deaktiviert. Es werden keine Nutzungssitzungen mit Clarity aufgezeichnet.")}
${serviceSection(openaiAdsSection, trackingConfig.providerRelease.openaiAds, "OpenAI Ads zur Zuordnung erfolgreicher Kontaktanfragen zu Anzeigen in ChatGPT ist derzeit deaktiviert.")}
${thirdCountrySection}
${picDropSection}
${externalLinksSection}
${storageSection}
${rightsSection}
${complaintSection}
`;

const privacyPaths = new Set([
  "/datenschutz/",
  "/datenschutzerklaerung/",
]);

export const modernizePrivacyContent = (path: string, sourceHtml: string) =>
  privacyPaths.has(path) ? privacyContent : sourceHtml;
